[package]
name = "bin"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
tracing-bunyan-formatter = "0.3.2"
tracing-log = "0.1.2"
tracing-subscriber = {version = "0.3", features = ["env-filter"]}

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["run-for-all", "user-hooks"]
